### ISSUE TITLE
Segfault during plugin initiailization

### ISSUE THREAD

**Issue by hjanott** [naturerobots/move_base_flex#82] opened 2018-09-12 14:29 UTC
MBF segfaults in the plugin manager when for instance MBF fails to load a controller plugin and the function initializeControllerPlugin returns false.

**Comment by corot** [comment] 2018-10-14 18:34
Hi @hjanott, can you explain how to reproduce? Making initializeControllerPlugin return false doesn't crash. But maybe this got fixed with the recent changes. Could you retry with latest master? And if still crashes, send a stacktrace and a recipe on how to reproduce?
Thanks!

**Comment by spuetz** [comment] 2018-10-14 21:00
So yes @hjanott and I, we recognized that bug together. I'll test that again.

**Comment by spuetz** [comment] 2020-03-26 12:19
Close issue, since I cannot reproduce the bug.

**Closed as completed by spuetz** 2020-03-26 12:19 UTC
Labels: details needed
